language: generic

before_script:
  - git clone https://github.com/thinca/vim-themis --quiet --single-branch --depth 1 /tmp/vim-themis

script:
  - vim --version
  - /tmp/vim-themis/bin/themis test/ -r --reporter dot

notifications:
  email: false
