language: generic

install:
  - export VIM_VERSION=master
  - bash test/install-vim.sh
  - export PATH=$HOME/vim/bin:$PATH

before_script:
  - git clone --depth 1 --branch v1.5.4 --single-branch https://github.com/thinca/vim-themis /tmp/vim-themis

script:
  - vim --version
  - /tmp/vim-themis/bin/themis test/ -r --reporter dot

notifications:
  email: false
